import httpx, base64
from pyrogram import filters
from pyrogram.types import Message,InlineKeyboardButton,InlineKeyboardMarkup
from pyrogram.enums import *
from Exon import Abishnoi as app

@app.on_message(filters.command("upscale"))
async def upscale_image(client, message):
        try:
            # Check if the replied message contains a photo
            if message.reply_to_message and message.reply_to_message.photo:
                # Send a message indicating upscaling is in progress
                progress_msg = await message.reply_text(
                    "Upscaling your image, please wait..."
                )

                # Access the image file_id from the replied message
                image = message.reply_to_message.photo.file_id
                file_path = await client.download_media(image)

                with open(file_path, "rb") as image_file:
                    f = image_file.read()

                b = base64.b64encode(f).decode("utf-8")

                async with httpx.AsyncClient() as http_client:
                    response = await http_client.post(
                        "https://api.qewertyy.me/upscale",
                        data={"image_data": b},
                        timeout=None,
                    )

                # Save the upscaled image
                upscaled_file_path = "upscaled_image.png"
                with open(upscaled_file_path, "wb") as output_file:
                    output_file.write(response.content)

                # Delete the progress message
                await progress_msg.delete()

                # Send the upscaled image as a PNG file
                await client.send_document(
                    message.chat.id,
                    document=upscaled_file_path,
                    caption=f"**Generated BY:** @{app.me.username}",
                )
            else:
                await message.reply_text("Please reply to an image to upscale it.")

        except Exception as e:
            print(f"Failed to upscale the image: {e}")
            await message.reply_text("Failed to upscale the image. Please try again later.")
            # You may want to handle the error more gracefully here



__mod_name__ = "Aɪ"

__help__ ="""
Hᴇʀᴇ Aʀᴇ Tʜᴇ Aɪ Mᴏᴅᴜʟᴇꜱ Lɪꜱᴛ Aᴠᴀɪʟᴀʙʟᴇ Iɴ Sᴜᴢᴜᴍᴇ

    ➢ /ask , /chat*:* ᴛᴏ ɢᴇᴛ ꜱᴇᴀʀᴄʜ ʀᴇꜱᴜʟᴛꜱ ꜰʀᴏᴍ Cʜᴀᴛ Gᴘᴛ.

    ➢ /bard*:* ᴛᴏ ɢᴇᴛ ꜱᴇᴀʀᴄʜ ʀᴇꜱᴜʟᴛꜱ ꜰʀᴏᴍ Bᴀʀᴅ Aɪ.

    ➢ /rmbg*:* ᴛᴏ ʀᴇᴍᴏᴠᴇ ʙᴀᴄᴋɢʀᴏᴜɴᴅ ᴏꜰ ᴛʜᴇ ᴀɴʏ ɪᴍᴀɢᴇ ᴛʜʀᴏᴜɢʜ Aɪ.

    ➢ /upscale*:* Tᴏ ɪɴᴄʀᴇᴀꜱᴇꜱ ᴛʜᴇ Qᴜᴀʟɪᴛʏ ᴏꜰ ᴀɴ ɪᴍᴀɢᴇ ᴛʜʀᴏᴜɢʜ Aɪ.

    ➢ /imagine , /draw*:* ɢᴇᴛ ᴛʜᴇ Aɪ ɢᴇɴᴇʀᴀᴛᴇᴅ ɪᴍᴀɢᴇꜱ ʙʏ ᴘʀᴏᴠɪᴅɪɴɢ ᴛʜᴇ ᴅᴇꜱᴄʀɪᴘᴛɪᴏɴ
"""


from Exon.modules.language import gs


def get_help(chat):
    return gs(chat, "ai_help")

